name: Update Yahoo Market Data (Simplified)

# SIMPLER VERSION: Runs every 15 minutes during extended hours
# You can rely on the Python script to check if market is actually open

on:
  schedule:
    # INTRADAY: Every 15 minutes, 1:00 PM - 9:00 PM UTC (covers market hours in both timezones)
    # This is 7:00 AM - 3:00 PM MDT or 9:00 AM - 5:00 PM EDT
    # The Python script will check if market is actually open
    - cron: '0,15,30,45 13-20 * * 1-5'
    
    # DAILY: 6:00 AM MDT = 12:00 PM UTC
    - cron: '0 12 * * *'
    
    # WEEKLY: Sunday 6:00 PM MDT = Monday 12:00 AM UTC
    - cron: '0 0 * * 1'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of update'
        required: true
        default: 'intraday'
        type: choice
        options:
          - intraday
          - daily
          - weekly

jobs:
  update-market-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance firebase-admin pytz
      
      - name: Determine update type
        id: update_type
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "type=${{ github.event.inputs.update_type }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.schedule }}" == "0 12 * * *" ]; then
            echo "type=daily" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.schedule }}" == "0 0 * * 1" ]; then
            echo "type=weekly" >> $GITHUB_OUTPUT
          else
            echo "type=intraday" >> $GITHUB_OUTPUT
          fi
      
      - name: Update market data
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          echo "Running ${{ steps.update_type.outputs.type }} update..."
          python yahoo_market_updater.py ${{ steps.update_type.outputs.type }}
      
      - name: Report results
        if: always()
        run: |
          echo "Update type: ${{ steps.update_type.outputs.type }}"
          echo "Completed at: $(date -u)"
          echo "Completed at: $(TZ='America/Denver' date) MDT"
